### PR TITLE
Battery patch Offset (0x38) 16 bit to 8 bit 

### PR DESCRIPTION
**Pull request by hla63**
Don't know if its really needed for battery but Hackintosh needs 8 bit register to works properly.

### CODE REVIEW

**Comment by AndresGarciaSobrado91** [comment]
Hi @hla63 ! Thank you for your help! I will reject this PR because (for my luck) this specific model does not need this battery patch. Let me show you:
battery
battery 2

So none 8-bit longer var is used, we are battery-reads safe.

Again, thank you for your support. Best regards.

**Comment by hla63** [comment]
Bat1 acpi error show on Hackintool log : 
Capture d’écran 2020-12-02 à 17 50 09
 I found a way to remove this _Sta method should be something like this: 
 Method (_STA, 0, NotSerialized)
 {
   If (^^ADP1.BFLG)
   {
     Return (0x1F)
   }
   Else
   {
     Return (0x0F)
   }
 }

Capture d’écran 2020-12-02 à 18 17 38

**Comment by hla63** [comment]
I found another way : 
rename BAT1 STA to XSTA  Find 1206015F 53425F14 1F5F5354 4100 Replace 1206015F 53425F14 1F585354 4100
[SSDT-STA.aml.zip](https://github.com/AndresGarciaSobrado91/MSI-Modern15-Hackintosh/files/5651953/SSDT-STA.aml.zip)

**Comment by AndresGarciaSobrado91** [comment]
Great! Thank you @hla63 !! :)

**Pull request closed without merging**
